### ISSUE TITLE
https://www.code.angularjs.org/ is down URGENT!!! 

### ISSUE THREAD

**Issue by Sumeetgrg** [angular/code.angularjs.org#40] opened 2017-08-30 07:24 UTC
**Our production is halted! URGENT!!**

We are referring domain: https://code.angularjs.org/1.2.12..
https://angularjs.org/ is down too..

**Comment by gkalpak** [comment] 2017-08-30 09:03
Duplicate of angular/angularjs.org#221.

**Closed by gkalpak** 2017-08-30 09:03 UTC
